name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Déclenche l'action sur les modifications de la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation de l'environnement Ubuntu pour exécuter l'action

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Clone le repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Configure Docker Buildx pour construire des images multiplateformes

    - name: Log in to GitHub Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}  # Utilise l'authentification GitHub
        password: ${{ secrets.GITHUB_TOKEN }}  # Utilise le token GitHub pour se connecter au registre

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .  # Le contexte de la construction de l'image est le répertoire actuel
        file: ./Dockerfile  # Chemin vers le Dockerfile
        push: true  # Push l'image vers le registre GitHub Packages
        tags: ${{ github.repository }}:latest  # Tag de l'image, utilisez le nom du repository pour l'image
